### PR TITLE
Fix conformance for camera example and Operational Credentials cluster

### PR DESCRIPTION
**Pull request by lboue**
Following this PR:
- https://github.com/project-chip/connectedhomeip/pull/37640

**Before** 
```
Application is failing the Cluster Specification as follows: 

  - ⚠ Check Cluster Compliance on endpoint: 0, cluster: Operational Credentials server, mandatory command: SetVidVerificationStatement incoming needs to be enabled
  - ⚠ Check Cluster Compliance on endpoint: 0, cluster: Operational Credentials server, mandatory command: SignVidVerificationRequest incoming needs to be enabled
  - ⚠ Check Cluster Compliance on endpoint: 0, cluster: Operational Credentials server, mandatory command: SignVidVerificationResponse outgoing needs to be enabled
```

**After**
No error

#### Testing

`./scripts/tools/zap/generate.py examples/camera-app/camera-common/camera-app.zap`

### CODE REVIEW

**Comment by andy31415** [comment]
@lboue it seems like camera app does not compile on linux anymore. I have restarted the CI check, however it is likely a real failure.

**Comment by lboue** [comment]
The issue was introduced by #37640 because there is missing references:
- undefined reference to `emberAfOperationalCredentialsClusterSetVidVerificationStatementCallback
- undefined reference to `emberAfOperationalCredentialsClusterSignVidVerificationRequestCallback

I can't find those methods in [operational-credentials-server.cpp](https://github.com/project-chip/connectedhomeip/blob/master/src/app/clusters/operational-credentials-server/operational-credentials-server.cpp)

**Error**
```
INFO    FAILED: chip-camera-app 
INFO    g++ -O0 -fPIC -Werror -Wl,--fatal-warnings -Wl,-z,defs -fdiagnostics-color -Wl,--gc-sections -pie @./chip-camera-app.rsp -o ./chip-camera-app
INFO    /usr/bin/ld: obj/gen/third_party/connectedhomeip/examples/camera-app/camera-common/zapgen/zap-generated/camera-common_zapgen.IMClusterCommandHandler.cpp.o: in function `chip::app::Clusters::OperationalCredentials::DispatchServerCommand(chip::app::CommandHandler*, chip::app::ConcreteCommandPath const&, chip::TLV::TLVReader&)':
INFO    /__w/connectedhomeip/connectedhomeip/out/linux-x64-camera/gen/third_party/connectedhomeip/examples/camera-app/camera-common/zapgen/zap-generated/IMClusterCommandHandler.cpp:447:(.text._ZN4chip3app8Clusters22OperationalCredentials21DispatchServerCommandEPNS0_14CommandHandlerERKNS0_19ConcreteCommandPathERNS_3TLV9TLVReaderE+0x649): undefined reference to `emberAfOperationalCredentialsClusterSetVidVerificationStatementCallback(chip::app::CommandHandler*, chip::app::ConcreteCommandPath const&, chip::app::Clusters::OperationalCredentials::Commands::SetVidVerificationStatement::DecodableType const&)'
INFO    /usr/bin/ld: /__w/connectedhomeip/connectedhomeip/out/linux-x64-camera/gen/third_party/connectedhomeip/examples/camera-app/camera-common/zapgen/zap-generated/IMClusterCommandHandler.cpp:456:(.text._ZN4chip3app8Clusters22OperationalCredentials21DispatchServerCommandEPNS0_14CommandHandlerERKNS0_19ConcreteCommandPathERNS_3TLV9TLVReaderE+0x6f6): undefined reference to `emberAfOperationalCredentialsClusterSignVidVerificationRequestCallback(chip::app::CommandHandler*, chip::app::ConcreteCommandPath const&, chip::app::Clusters::OperationalCredentials::Commands::SignVidVerificationRequest::DecodableType const&)'
```
