### PR TITLE
Fix compiler error on tip of tree

### PR DESCRIPTION
**Pull request by tehampson**
Compiling chip-tool on tip of tree fails with:

Issue was introduced in https://github.com/project-chip/connectedhomeip/pull/32459. I don't have the time to properly forward fix so just going with revert of section of code that was problematic with a TODO

```
2024-03-14 17:46:51 INFO    ../../examples/chip-tool/third_party/connectedhomeip/src/controller/AbstractDnssdDiscoveryController.cpp: In member function ‘virtual void chip::Controller::AbstractDnssdDiscoveryCont
roller::OnNodeDiscovered(const chip::Dnssd::DiscoveredNodeData&)’:
2024-03-14 17:46:51 INFO    ../../examples/chip-tool/third_party/connectedhomeip/src/controller/AbstractDnssdDiscoveryController.cpp:39:53: error: comparison between two arrays [-Werror=array-compare]
2024-03-14 17:46:51 INFO       39 |             discoveredNode.resolutionData.ipAddress == nodeData.resolutionData.ipAddress)
```

### CODE REVIEW

File: src/controller/AbstractDnssdDiscoveryController.cpp [hunk 1]
```diff
@@ -34,9 +34,10 @@ void AbstractDnssdDiscoveryController::OnNodeDiscovered(const chip::Dnssd::Disco
         {
             continue;
         }
+        // TODO Check if IP address are the same. Must account for `numIPs` in the list of `ipAddress`.
+        // Additionally, must NOT assume that the ordering is consistent.
         if (strcmp(discoveredNode.resolutionData.hostName, nodeData.resolutionData.hostName) == 0 &&
-            discoveredNode.resolutionData.port == nodeData.resolutionData.port &&
```
Comment (tcarmelveilleux) [inline src/controller/AbstractDnssdDiscoveryController.cpp:38]: To keep behavior same as before, suggest doing a loop comparison with numIPs., will be no worse and maybe better.

File: src/controller/AbstractDnssdDiscoveryController.cpp [hunk 2]
```diff
@@ -34,9 +34,10 @@ void AbstractDnssdDiscoveryController::OnNodeDiscovered(const chip::Dnssd::Disco
         {
             continue;
         }
+        // TODO Check if IP address are the same. Must account for `numIPs` in the list of `ipAddress`.
```
Comment (tcarmelveilleux) [inline src/controller/AbstractDnssdDiscoveryController.cpp:37]: Please open an issue, assign to original committer, a d put number in TODO

**Review by tcarmelveilleux — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]
