### ISSUE TITLE
[BUG] chip-cert-bins Docker image build is failing

### ISSUE THREAD

**Issue by rquidute** [project-chip/connectedhomeip#43129]
### Reproduction steps

 The chip-cert-bins Docker image build is failing after Thread Commissioning support was added to the codebase. The build configuration uses platform-mdns for chip-tool, which is now incompatible with the Thread Commissioner feature that was enabled by default.

Build Error
>   undefined reference to `mdns::Minimal::ParsePacket(mdns::Minimal::BytesRange const&,mdns::Minimal::ParserDelegate*)'collect2: error: ld returned 1 exit status
>   ninja: build stopped: subcommand failed
>   Exception: Command ['ninja', '-C', '/root/connectedhomeip/out/linux-arm64-chip-tool-ipv6only-platform-mdns'] failed: 1

Note: The Thread Commissioning was introduced by #42992

### Bug prevalence

always

### GitHub hash of the SDK that was being used

852d16667e4d1225850cee77c424ef2a69e931f1

### Platform

other

**Comment by bukepo** [comment]
This should be fixed by https://github.com/project-chip/connectedhomeip/pull/43029

**Comment by Pradeep-grl** [comment]
Issue has been fixed in PR: https://github.com/project-chip/connectedhomeip/pull/43029. Accordingly, closing this issue.
