### ISSUE TITLE
[YAML Tests] PR #11740 broke `./examples/placeholder/linux` apps

### ISSUE THREAD

**Issue by mikaelhm** [project-chip/connectedhomeip#11761]
#### Problem
Unable to build `app1` from `./examples/placeholder/linux/app1`

 * expected behavior
   attempted to build `app1` using this command
   ```sh
   ./scripts/examples/gn_build_test_example.sh app1
   ```
 * actual behavior
    Build failed with this log:
```sh
./scripts/examples/gn_build_test_example.sh app1

  WELCOME TO...

  ▄███▒  ░▓█  ░▓█ ░▓█▓ ▒█████▄
 ██▒ ▀█▒  ▒█   ▒█  ░█▒  ▒█░  █░
 █▓░      ▒██████  ░█▒  ▒█▄▄▄█░
 ▓█   █▒  ▒█   ▒█  ░█░  ▒█▀
 ░▓███▀  ░▓███░▓█▒ ░█░  ▒█

  ACTIVATOR! This sets your shell environment variables.

Activating environment (setting environment variables):

  Setting environment variables for CIPD package manager...done
  Setting environment variables for Python environment.....done
  Setting environment variables for Host tools.............done

Checking the environment:

20211112 23:29:38 WRN Current uname (5.4.0-1045-raspi #49-Ubuntu SMP PREEMPT Wed Sep 29 17:49:16 UTC 2021 aarch64) does not match Bootstrap uname (5.4.0-1044-raspi #48-Ubuntu SMP PREEMPT Thu Sep 9 15:24:01 UTC 2021 aarch64), you may need to rerun bootstrap on this system
20211112 23:29:38 INF Environment passes all checks!

Environment looks good, you are ready to go!

🚀 Executing: git log -1 --format={"hash": "%H","timestamp": %ct}
🔍 Git commit: 98b43b32758cbfd8f643ef0a365cab9e0d9dcfde from Thu Nov 04 2021 19:04:58 GMT+0000 (Coordinated Universal Time)
🚀 Executing: npm run build-backend

> zap@2021.10.29 build-backend /home/ubuntu/pi-test-harness/chip-certification-tool/backend/third_party/connectedhomeip/repo/third_party/zap/repo
> npx tsc --build ./tsconfig.json

🚀 Executing: node dist/src-electron/main-process/electron-main.js generate --noUi --noServer --stateDirectory ~/.zap --zcl /home/ubuntu/pi-test-harness/chip-certification-tool/backend/third_party/connectedhomeip/repo/src/app/zap-templates/zcl/zcl.json --generationTemplate /home/ubuntu/pi-test-harness/chip-certification-tool/backend/third_party/connectedhomeip/repo/src/app/zap-templates/app-templates.json --out /home/ubuntu/pi-test-harness/chip-certification-tool/backend/third_party/connectedhomeip/repo/scripts/examples/../../out/debug/placeholder/app1/zap-generated /home/ubuntu/pi-test-harness/chip-certification-tool/backend/third_party/connectedhomeip/repo/scripts/examples/../../examples/placeholder/linux/apps/app1/config.zap
🤖 ZAP generation started: 
    🔍 input files: /home/ubuntu/pi-test-harness/chip-certification-tool/backend/third_party/connectedhomeip/repo/scripts/examples/../../examples/placeholder/linux/apps/app1/config.zap
    🔍 output pattern: /home/ubuntu/pi-test-harness/chip-certification-tool/backend/third_party/connectedhomeip/repo/scripts/examples/../../out/debug/placeholder/app1/zap-generated
    🔍 using templates: /home/ubuntu/pi-test-harness/chip-certification-tool/backend/third_party/connectedhomeip/repo/src/app/zap-templates/app-templates.json
    🔍 using zcl data: /home/ubuntu/pi-test-harness/chip-certification-tool/backend/third_party/connectedhomeip/repo/src/app/zap-templates/zcl/zcl.json
    🔍 zap version: ver. 2021.10.29, featureLevel 63, commit: 98b43b32758cbfd8f643ef0a365cab9e0d9dcfde from 2021-11-04T19:04:58.000Z
🕐 Setup time: 7s 797ms 
👉 using input file: /home/ubuntu/pi-test-harness/chip-certification-tool/backend/third_party/connectedhomeip/repo/scripts/examples/../../examples/placeholder/linux/apps/app1/config.zap
👉 using output destination: /home/ubuntu/pi-test-harness/chip-certification-tool/backend/third_party/connectedhomeip/repo/scripts/examples/../../out/debug/placeholder/app1/zap-generated
🕐 File loading time: 236ms
🤖 Generating files:
    ✍  /home/ubuntu/pi-test-harness/chip-certification-tool/backend/third_party/connectedhomeip/repo/out/debug/placeholder/app1/zap-generated/gen_tokens.h
    ✍  /home/ubuntu/pi-test-harness/chip-certification-tool/backend/third_party/connectedhomeip/repo/out/debug/placeholder/app1/zap-generated/PluginApplicationCallbacks.h
    ✍  /home/ubuntu/pi-test-harness/chip-certification-tool/backend/third_party/connectedhomeip/repo/out/debug/placeholder/app1/zap-generated/callback-stub.cpp
    ✍  /home/ubuntu/pi-test-harness/chip-certification-tool/backend/third_party/connectedhomeip/repo/out/debug/placeholder/app1/zap-generated/gen_config.h
    ✍  /home/ubuntu/pi-test-harness/chip-certification-tool/backend/third_party/connectedhomeip/repo/out/debug/placeholder/app1/zap-generated/endpoint_config.h
    ✍  /home/ubuntu/pi-test-harness/chip-certification-tool/backend/third_party/connectedhomeip/repo/out/debug/placeholder/app1/zap-generated/CHIPClientCallbacks.h
    ✍  /home/ubuntu/pi-test-harness/chip-certification-tool/backend/third_party/connectedhomeip/repo/out/debug/placeholder/app1/zap-generated/CHIPClientCallbacks.cpp
    ✍  /home/ubuntu/pi-test-harness/chip-certification-tool/backend/third_party/connectedhomeip/repo/out/debug/placeholder/app1/zap-generated/CHIPClusters.h
    ✍  /home/ubuntu/pi-test-harness/chip-certification-tool/backend/third_party/connectedhomeip/repo/out/debug/placeholder/app1/zap-generated/CHIPClusters.cpp
    ✍  /home/ubuntu/pi-test-harness/chip-certification-tool/backend/third_party/connectedhomeip/repo/out/debug/placeholder/app1/zap-generated/attribute-size.cpp
    ✍  /home/ubuntu/pi-test-harness/chip-certification-tool/backend/third_party/connectedhomeip/repo/out/debug/placeholder/app1/zap-generated/IMClusterCommandHandler.cpp
🕐 Generation time: 1s 58ms 
😎 All done: 23s 90ms.
🚀 Executing: git log -1 --format={"hash": "%H","timestamp": %ct}
🔍 Git commit: 98b43b32758cbfd8f643ef0a365cab9e0d9dcfde from Thu Nov 04 2021 19:04:58 GMT+0000 (Coordinated Universal Time)
🚀 Executing: npm run build-backend

> zap@2021.10.29 build-backend /home/ubuntu/pi-test-harness/chip-certification-tool/backend/third_party/connectedhomeip/repo/third_party/zap/repo
> npx tsc --build ./tsconfig.json

🚀 Executing: node dist/src-electron/main-process/electron-main.js generate --noUi --noServer --stateDirectory ~/.zap --zcl /home/ubuntu/pi-test-harness/chip-certification-tool/backend/third_party/connectedhomeip/repo/src/app/zap-templates/zcl/zcl.json --generationTemplate /home/ubuntu/pi-test-harness/chip-certification-tool/backend/third_party/connectedhomeip/repo/scripts/examples/../../examples/placeholder/linux/../templates/templates.json --out /home/ubuntu/pi-test-harness/chip-certification-tool/backend/third_party/connectedhomeip/repo/scripts/examples/../../out/debug/placeholder/app1/zap-generated /home/ubuntu/pi-test-harness/chip-certification-tool/backend/third_party/connectedhomeip/repo/scripts/examples/../../examples/placeholder/linux/apps/app1/config.zap
🤖 ZAP generation started: 
    🔍 input files: /home/ubuntu/pi-test-harness/chip-certification-tool/backend/third_party/connectedhomeip/repo/scripts/examples/../../examples/placeholder/linux/apps/app1/config.zap
    🔍 output pattern: /home/ubuntu/pi-test-harness/chip-certification-tool/backend/third_party/connectedhomeip/repo/scripts/examples/../../out/debug/placeholder/app1/zap-generated
    🔍 using templates: /home/ubuntu/pi-test-harness/chip-certification-tool/backend/third_party/connectedhomeip/repo/scripts/examples/../../examples/placeholder/linux/../templates/templates.json
    🔍 using zcl data: /home/ubuntu/pi-test-harness/chip-certification-tool/backend/third_party/connectedhomeip/repo/src/app/zap-templates/zcl/zcl.json
    🔍 zap version: ver. 2021.10.29, featureLevel 63, commit: 98b43b32758cbfd8f643ef0a365cab9e0d9dcfde from 2021-11-04T19:04:58.000Z
🕐 Setup time: 32s 911ms 
👉 using input file: /home/ubuntu/pi-test-harness/chip-certification-tool/backend/third_party/connectedhomeip/repo/scripts/examples/../../examples/placeholder/linux/apps/app1/config.zap
👉 using output destination: /home/ubuntu/pi-test-harness/chip-certification-tool/backend/third_party/connectedhomeip/repo/scripts/examples/../../out/debug/placeholder/app1/zap-generated
🕐 File loading time: 1s 870ms
🤖 Generating files:
    ✍  /home/ubuntu/pi-test-harness/chip-certification-tool/backend/third_party/connectedhomeip/repo/out/debug/placeholder/app1/zap-generated/test/Commands.h
🕐 Generation time: 1s 110ms 
😎 All done: 50s 713ms.
Done. Made 82 targets from 93 files in 923ms
ninja: Entering directory `/home/ubuntu/pi-test-harness/chip-certification-tool/backend/third_party/connectedhomeip/repo/scripts/examples/../../out/debug/placeholder'
[122/421] c++ obj/chip-app1.main.cpp.o
FAILED: obj/chip-app1.main.cpp.o 
aarch64-linux-gnu-g++ -MMD -MF obj/chip-app1.main.cpp.o.d -Wconversion -O0 -g2 -fno-common -ffunction-sections -fdata-sections -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -Wall -Werror -Wextra -Wshadow -Wunreachable-code -Wvla -Wno-deprecated-declarations -Wno-unknown-warning-option -Wno-maybe-uninitialized -Wno-missing-field-initializers -Wno-unused-parameter -Wno-psabi -Wno-cast-function-type -fdiagnostics-color -fno-strict-aliasing -D_REENTRANT -I/usr/include/gio-unix-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -std=gnu++14 -fno-rtti -Wnon-virtual-dtor -DCHIP_HAVE_CONFIG_H=1 -I../../../examples/placeholder/linux/include -I../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1 -I../../../examples/placeholder/linux/third_party/connectedhomeip/src/include -I../../../examples/placeholder/linux/third_party/connectedhomeip/src -Igen/include -I../../../examples/placeholder/linux/third_party/connectedhomeip/zzz_generated/app-common -I/home/ubuntu/pi-test-harness/chip-certification-tool/backend/third_party/connectedhomeip/repo/examples/placeholder/linux/apps/app1/include -I/home/ubuntu/pi-test-harness/chip-certification-tool/backend/third_party/connectedhomeip/repo/config/standalone -I../../../examples/placeholder/linux/third_party/connectedhomeip/third_party/nlassert/repo/include -I../../../examples/placeholder/linux/third_party/connectedhomeip/third_party/nlio/repo/include -I../../../examples/placeholder/linux/third_party/connectedhomeip/third_party/inipp/repo/inipp -I../../../examples/placeholder/linux/third_party/connectedhomeip/zzz_generated -I../../../examples/placeholder/linux/third_party/connectedhomeip/examples/platform/linux -c ../../../examples/placeholder/linux/main.cpp -o obj/chip-app1.main.cpp.o
In file included from ../../../examples/placeholder/linux/include/MatterCallbacks.h:28,
                 from ../../../examples/placeholder/linux/main.cpp:20:
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h: In member function ‘CHIP_ERROR Test_TC_DM_1_3_Simulated::TestQueryInteractionModelVersion_2()’:
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h:157:43: error: ‘mEndpointId’ was not declared in this scope; did you mean ‘endpoint’?
  157 |         const chip::EndpointId endpoint = mEndpointId.HasValue() ? mEndpointId.Value() : 0;
      |                                           ^~~~~~~~~~~
      |                                           endpoint
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h:157:43: note: maximum limit of 1000 namespaces searched for ‘mEndpointId’
In file included from ../../../examples/placeholder/linux/include/MatterCallbacks.h:28,
                 from ../../../examples/placeholder/linux/main.cpp:20:
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h: In member function ‘CHIP_ERROR Test_TC_DM_1_3_Simulated::TestQueryVendorName_3()’:
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h:170:43: error: ‘mEndpointId’ was not declared in this scope; did you mean ‘endpoint’?
  170 |         const chip::EndpointId endpoint = mEndpointId.HasValue() ? mEndpointId.Value() : 0;
      |                                           ^~~~~~~~~~~
      |                                           endpoint
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h:170:43: note: maximum limit of 1000 namespaces searched for ‘mEndpointId’
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h: In member function ‘CHIP_ERROR Test_TC_DM_1_3_Simulated::TestQueryVendorID_4()’:
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h:181:43: error: ‘mEndpointId’ was not declared in this scope; did you mean ‘endpoint’?
  181 |         const chip::EndpointId endpoint = mEndpointId.HasValue() ? mEndpointId.Value() : 0;
      |                                           ^~~~~~~~~~~
      |                                           endpoint
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h:181:43: note: maximum limit of 1000 namespaces searched for ‘mEndpointId’
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h: In member function ‘CHIP_ERROR Test_TC_DM_1_3_Simulated::TestQueryProductName_5()’:
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h:192:43: error: ‘mEndpointId’ was not declared in this scope; did you mean ‘endpoint’?
  192 |         const chip::EndpointId endpoint = mEndpointId.HasValue() ? mEndpointId.Value() : 0;
      |                                           ^~~~~~~~~~~
      |                                           endpoint
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h:192:43: note: maximum limit of 1000 namespaces searched for ‘mEndpointId’
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h: In member function ‘CHIP_ERROR Test_TC_DM_1_3_Simulated::TestQueryProductID_6()’:
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h:203:43: error: ‘mEndpointId’ was not declared in this scope; did you mean ‘endpoint’?
  203 |         const chip::EndpointId endpoint = mEndpointId.HasValue() ? mEndpointId.Value() : 0;
      |                                           ^~~~~~~~~~~
      |                                           endpoint
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h:203:43: note: maximum limit of 1000 namespaces searched for ‘mEndpointId’
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h: In member function ‘CHIP_ERROR Test_TC_DM_1_3_Simulated::TestQueryUserLabel_7()’:
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h:214:43: error: ‘mEndpointId’ was not declared in this scope; did you mean ‘endpoint’?
  214 |         const chip::EndpointId endpoint = mEndpointId.HasValue() ? mEndpointId.Value() : 0;
      |                                           ^~~~~~~~~~~
      |                                           endpoint
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h:214:43: note: maximum limit of 1000 namespaces searched for ‘mEndpointId’
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h: In member function ‘CHIP_ERROR Test_TC_DM_1_3_Simulated::TestQueryUserLocation_8()’:
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h:225:43: error: ‘mEndpointId’ was not declared in this scope; did you mean ‘endpoint’?
  225 |         const chip::EndpointId endpoint = mEndpointId.HasValue() ? mEndpointId.Value() : 0;
      |                                           ^~~~~~~~~~~
      |                                           endpoint
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h:225:43: note: maximum limit of 1000 namespaces searched for ‘mEndpointId’
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h: In member function ‘CHIP_ERROR Test_TC_DM_1_3_Simulated::TestQueryHardwareVersion_9()’:
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h:236:43: error: ‘mEndpointId’ was not declared in this scope; did you mean ‘endpoint’?
  236 |         const chip::EndpointId endpoint = mEndpointId.HasValue() ? mEndpointId.Value() : 0;
      |                                           ^~~~~~~~~~~
      |                                           endpoint
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h:236:43: note: maximum limit of 1000 namespaces searched for ‘mEndpointId’
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h: In member function ‘CHIP_ERROR Test_TC_DM_1_3_Simulated::TestQueryHardwareVersionString_10()’:
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h:247:43: error: ‘mEndpointId’ was not declared in this scope; did you mean ‘endpoint’?
  247 |         const chip::EndpointId endpoint = mEndpointId.HasValue() ? mEndpointId.Value() : 0;
      |                                           ^~~~~~~~~~~
      |                                           endpoint
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h:247:43: note: maximum limit of 1000 namespaces searched for ‘mEndpointId’
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h: In member function ‘CHIP_ERROR Test_TC_DM_1_3_Simulated::TestQuerySoftwareVersion_11()’:
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h:259:43: error: ‘mEndpointId’ was not declared in this scope; did you mean ‘endpoint’?
  259 |         const chip::EndpointId endpoint = mEndpointId.HasValue() ? mEndpointId.Value() : 0;
      |                                           ^~~~~~~~~~~
      |                                           endpoint
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h:259:43: note: maximum limit of 1000 namespaces searched for ‘mEndpointId’
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h: In member function ‘CHIP_ERROR Test_TC_DM_1_3_Simulated::TestQuerySoftwareVersionString_12()’:
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h:270:43: error: ‘mEndpointId’ was not declared in this scope; did you mean ‘endpoint’?
  270 |         const chip::EndpointId endpoint = mEndpointId.HasValue() ? mEndpointId.Value() : 0;
      |                                           ^~~~~~~~~~~
      |                                           endpoint
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h:270:43: note: maximum limit of 1000 namespaces searched for ‘mEndpointId’
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h: In member function ‘CHIP_ERROR Test_TC_DM_1_3_Simulated::TestQueryManufacturingDate_13()’:
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h:282:43: error: ‘mEndpointId’ was not declared in this scope; did you mean ‘endpoint’?
  282 |         const chip::EndpointId endpoint = mEndpointId.HasValue() ? mEndpointId.Value() : 0;
      |                                           ^~~~~~~~~~~
      |                                           endpoint
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h:282:43: note: maximum limit of 1000 namespaces searched for ‘mEndpointId’
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h: In member function ‘CHIP_ERROR Test_TC_DM_1_3_Simulated::TestQueryPartNumber_14()’:
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h:293:43: error: ‘mEndpointId’ was not declared in this scope; did you mean ‘endpoint’?
  293 |         const chip::EndpointId endpoint = mEndpointId.HasValue() ? mEndpointId.Value() : 0;
      |                                           ^~~~~~~~~~~
      |                                           endpoint
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h:293:43: note: maximum limit of 1000 namespaces searched for ‘mEndpointId’
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h: In member function ‘CHIP_ERROR Test_TC_DM_1_3_Simulated::TestQueryProductURL_15()’:
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h:304:43: error: ‘mEndpointId’ was not declared in this scope; did you mean ‘endpoint’?
  304 |         const chip::EndpointId endpoint = mEndpointId.HasValue() ? mEndpointId.Value() : 0;
      |                                           ^~~~~~~~~~~
      |                                           endpoint
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h:304:43: note: maximum limit of 1000 namespaces searched for ‘mEndpointId’
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h: In member function ‘CHIP_ERROR Test_TC_DM_1_3_Simulated::TestQueryProductLabel_16()’:
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h:315:43: error: ‘mEndpointId’ was not declared in this scope; did you mean ‘endpoint’?
  315 |         const chip::EndpointId endpoint = mEndpointId.HasValue() ? mEndpointId.Value() : 0;
      |                                           ^~~~~~~~~~~
      |                                           endpoint
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h:315:43: note: maximum limit of 1000 namespaces searched for ‘mEndpointId’
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h: In member function ‘CHIP_ERROR Test_TC_DM_1_3_Simulated::TestQuerySerialNumber_17()’:
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h:326:43: error: ‘mEndpointId’ was not declared in this scope; did you mean ‘endpoint’?
  326 |         const chip::EndpointId endpoint = mEndpointId.HasValue() ? mEndpointId.Value() : 0;
      |                                           ^~~~~~~~~~~
      |                                           endpoint
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h:326:43: note: maximum limit of 1000 namespaces searched for ‘mEndpointId’
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h: In member function ‘CHIP_ERROR Test_TC_DM_1_3_Simulated::TestQueryLocalConfigDisabled_18()’:
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h:337:43: error: ‘mEndpointId’ was not declared in this scope; did you mean ‘endpoint’?
  337 |         const chip::EndpointId endpoint = mEndpointId.HasValue() ? mEndpointId.Value() : 0;
      |                                           ^~~~~~~~~~~
      |                                           endpoint
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h:337:43: note: maximum limit of 1000 namespaces searched for ‘mEndpointId’
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h: In member function ‘CHIP_ERROR Test_TC_DM_1_3_Simulated::TestQueryReachable_19()’:
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h:349:43: error: ‘mEndpointId’ was not declared in this scope; did you mean ‘endpoint’?
  349 |         const chip::EndpointId endpoint = mEndpointId.HasValue() ? mEndpointId.Value() : 0;
      |                                           ^~~~~~~~~~~
      |                                           endpoint
../../../examples/placeholder/linux/third_party/connectedhomeip/out/debug/placeholder/app1/zap-generated/test/Commands.h:349:43: note: maximum limit of 1000 namespaces searched for ‘mEndpointId’
At global scope:
cc1plus: error: unrecognized command line option ‘-Wno-unknown-warning-option’ [-Werror]
cc1plus: all warnings being treated as errors
[127/421] c++ obj/third_party/connectedhomeip/src/app/util/configuration.af-main-common.cpp.o
ninja: build stopped: subcommand failed.
```

 #### Proposed Solution
Based on the build error I think this was introduced in #11740

**Comment by mikaelhm** [comment]
@vivien-apple can you take a look at this?

**Comment by trombadore** [comment]
this will close once #11819 merges

**Comment by carol-apple** [comment]
Closing based on comment above by @trombadore
