### PR TITLE
Fix minimal mdns test

### LINKED ISSUE #7603: Link failure in minimal mdns on darwin
#### Problem
1. `git checkout 165291310d1d67945b9a3fa191c319fbcf100427`
2. `rm -rf out`
3. `env BUILD_TYPE=clang ./scripts/build/gn_gen.sh --args="is_clang=true"`
4. `env BUILD_TYPE=clang ./scripts/build/gn_build.sh`

On darwin I get:
```
Undefined symbols for architecture x86_64:
  "vtable for mdns::Minimal::IPv6Responder", referenced from:
      mdns::Minimal::IPv6Responder::IPv6Responder(mdns::Minimal::FullQName const&) in libMdnsTests.a(libMdnsTests.TestMinimalMdnsAllocator.cpp.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "mdns::Minimal::QueryResponderBase::AddAllResponses(chip::Inet::IPPacketInfo const*, mdns::Minimal::ResponderDelegate*)", referenced from:
      vtable for mdns::Minimal::QueryResponder<11ul> in libMdnsTests.a(libMdnsTests.TestMinimalMdnsAllocator.cpp.o)
  "mdns::Minimal::QueryResponderBase::AddResponder(mdns::Minimal::RecordResponder*)", referenced from:
      chip::Mdns::QueryResponderAllocator<10ul>::AddAllocatedResponder(mdns::Minimal::RecordResponder*) in libMdnsTests.a(libMdnsTests.TestMinimalMdnsAllocator.cpp.o)
  "vtable for mdns::Minimal::IPv4Responder", referenced from:
      mdns::Minimal::IPv4Responder::IPv4Responder(mdns::Minimal::FullQName const&) in libMdnsTests.a(libMdnsTests.TestMinimalMdnsAllocator.cpp.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "mdns::Minimal::QueryResponderBase::QueryResponderBase(mdns::Minimal::Internal::QueryResponderInfo*, unsigned long)", referenced from:
      mdns::Minimal::QueryResponder<11ul>::QueryResponder() in libMdnsTests.a(libMdnsTests.TestMinimalMdnsAllocator.cpp.o)
  "mdns::Minimal::QueryResponderBase::Init()", referenced from:
      chip::Mdns::QueryResponderAllocator<10ul>::Clear() in libMdnsTests.a(libMdnsTests.TestMinimalMdnsAllocator.cpp.o)
      mdns::Minimal::QueryResponder<11ul>::QueryResponder() in libMdnsTests.a(libMdnsTests.TestMinimalMdnsAllocator.cpp.o)
  "mdns::Minimal::FullQName::operator==(mdns::Minimal::FullQName const&) const", referenced from:
      (anonymous namespace)::TestQueryAllocatorQName(_nlTestSuite*, void*) in libMdnsTests.a(libMdnsTests.TestMinimalMdnsAllocator.cpp.o)
      (anonymous namespace)::TestQueryAllocatorQNameArray(_nlTestSuite*, void*) in libMdnsTests.a(libMdnsTests.TestMinimalMdnsAllocator.cpp.o)
      mdns::Minimal::FullQName::operator!=(mdns::Minimal::FullQName const&) const in libMdnsTests.a(libMdnsTests.TestMinimalMdnsAllocator.cpp.o)
ld: symbol(s) not found for architecture x86_64
```

This is fallout from #7528 according to git bisect.  @cecille 

 #### Proposed Solution
Not sure yet.

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
#### Problem
mdns tests fail to link on Darwin. 

#### Change overview
Puts the minimal mdns test in the right dir, so it links.

Fixes https://github.com/project-chip/connectedhomeip/issues/7603

#### Testing
Verified that:
1. `./gn_build.sh` now works on Darwin
2. The test is still being run (including on darwin): I changed it in a way that should make it fail and it failed for me.

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
seems similar/related to #7600 

added checkmark to both to have at least one go through.

**Review by cecille — APPROVED** [review]
Thanks, Boris - sorry about that.

**Comment by bzbarsky-apple** [comment]
> Thanks, Boris - sorry about that.

It's not a problem; these things totally happen.  I'm sorry we don't have CI to catch this; working on that.

**Review by jelderton — APPROVED** [review]

**Comment by andy31415** [comment]
Hotfix admin-merge to bypass our very large CI queue at the moment
