### PR TITLE
Add CONFIG_MBEDTLS_HKDF_C=y to some esp32 defaults.

### PR DESCRIPTION
**Pull request by andy31415**
This seems to be required, otherwise I get errors like:

```
config/esp32/third_party/connectedhomeip/src/crypto/CHIPCryptoPALmbedTLS.cpp:330: undefined reference to `mbedtls_hkdf'
```

### CODE REVIEW

**Comment by andy31415** [comment]
Marking as hotfix: this fixes some build failures after #26608 - not all sdk default files were updated. This updates some more, however @wqx6 please verify if any other files need updating (like `examples/all-clusters-app/esp32/sdkconfig.defaults.esp32c6` or similar) or if my update of `examples/lighting-app/esp32/sdkconfig.defaults.esp32c6` and similar need need reverting.

**Comment by wqx6** [comment]
> Marking as hotfix: this fixes some build failures after #26608 - not all sdk default files were updated. This updates some more, however @wqx6 please verify if any other files need updating (like `examples/all-clusters-app/esp32/sdkconfig.defaults.esp32c6` or similar) or if my update of `examples/lighting-app/esp32/sdkconfig.defaults.esp32c6` and similar need need reverting.

`sdkconfig.defaults.<target_name>` files don't need updating, because when we use `idf.py set-target <target_name>` both `sdkconfig.defaults` and `sdkconfig.defaults.<target_name>` will be applied.
