### PR TITLE
Fix compilation error in lock-app and temperature-measurement-app

### PR DESCRIPTION
**Pull request by PSONALl**
#### Problem
1. Compilation fails for Lock app and Temperature App after merge: #7423 
2. M5stack or other device types support is mentioned in readme of both apps but actually not present
#### Change overview
* Added path to diagnostic-logs-server cluster in CMakelist.txt for both apps 
* Removed other device types from readme and Kconfig.projbuild

#### Testing
* Tested with chip-device-ctrl

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]

**Review by dhrishi — APPROVED** [review]

**Review by mspang — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]
Are we not building these in CI?

**Comment by dhrishi** [comment]
>Are we not building these in CI?

@bzbarsky-apple Nope. AFAIK, we only build all-clusters-app for ESP32. We can add it if that's okay

**Comment by woody-apple** [comment]
@saurabhst @msandstedt @Damian-Nordic @jepenven-silabs ?

**Review by saurabhst — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
> We can add it if that's okay

Yes, please!
