### ISSUE TITLE
[Build] NXP Zephyr unit-test build fails compiling host-only case_capture tests

### ISSUE THREAD

**Issue by Harshith-GRL** [project-chip/connectedhomeip#74087]
### Build issue(s)

`nxp-rw61x-zephyr-unit-test` fails to compile `src/controller/python/matter/case_capture/tests`:
https://github.com/project-chip/connectedhomeip/actions/runs/34523974898/job/103028223930

```
CASEHandshakeMetricsRecord.h:81:56: error: static assertion failed:
  PychipCASEHandshakeMetricsRecord::peerTransportAddress is too small to hold a rendered PeerAddress.
  note: the comparison reduces to '(108 <= 80)'
CompletedCASEHandshakeQueue.h:56:10: error: 'mutex' in namespace 'std' does not name a type
```

**Root cause:** the suite is listed unconditionally in `src/BUILD.gn`, and the Zephyr
build reaches that group through `config/nxp/chip-gn/BUILD.gn` -> `${chip_root}/src:tests`.
That pulls host-only Python-controller code onto an embedded toolchain, where it breaks
two ways:

1. `kCASEHandshakeMetricsPeerAddressMaxLength` is a hardcoded 80, sized against a host
   measurement. `PeerAddress::kMaxToStringSize` is platform-dependent -
   `InterfaceId::kMaxIfNameLength` is `IF_NAMESIZE` (16) on Linux/macOS but
   `Z_DEVICE_MAX_NAME_LEN` (48) on Zephyr, giving 76 vs 108.
2. Zephyr's libstdc++ is built without gthreads, so `<mutex>`, `<condition_variable>`
   and `<thread>` are effectively empty headers.

Introduced by #73619.

### Platform

other

### Anything else?

The code is the native half of a Python ctypes module and only ever links into
`_ChipDeviceCtrl.so`, so the fix is to gate the test suite to host platforms rather than
make the queue portable. PR to follow.
