### PR TITLE
Fix linux bridge-app clang build

### PR DESCRIPTION
**Pull request by rgoliver**
#### Problem
Clang build was getting errors related to using namespace directive in header file. Introduced in #19487
```
Step #4 - "Linux": 2022-06-20 14:13:37 INFO    In file included from ../../examples/bridge-app/linux/main.cpp:46:
Step #4 - "Linux": 2022-06-20 14:13:37 INFO    ../../examples/bridge-app/linux/include/Device.h:29:28: error: using namespace directive in global context in header [-Werror,-Wheader-hygiene]
Step #4 - "Linux": 2022-06-20 14:13:37 INFO    using namespace chip::app::Clusters;
Step #4 - "Linux": 2022-06-20 14:13:37 INFO                               ^
Step #4 - "Linux": 2022-06-20 14:13:37 INFO    ../../examples/bridge-app/linux/include/Device.h:30:38: error: using namespace directive in global context in header [-Werror,-Wheader-hygiene]
Step #4 - "Linux": 2022-06-20 14:13:37 INFO    using namespace chip::app::Clusters::BridgedActions;
```

#### Change overview
Remove `using namespace` from the header file.

#### Testing
Built linux bridge-app using clang.

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
fast trck: build failure fix
