### PR TITLE
Fix wrong uint64_t print

### LINKED ISSUE #4284: Mac build broken by printing node ids as `%lu`
#### Problem
```
../../src/app/tests/integration/chip_im_initiator.cpp:86:68: error: format specifies type 'unsigned long' but the argument has type 'chip::NodeId' (aka 'unsigned long long') [-Werror,-Wformat]
    printf("\nSend invoke command request message to Node: %lu\n", chip::kTestDeviceNodeId);
                                                           ~~~     ^~~~~~~~~~~~~~~~~~~~~~~
                                                           %llu
1 error generated.
```

 #### Proposed Solution
Always use `PRIu64` for printing `uint64_t`, including node ids.

Regression from https://github.com/project-chip/connectedhomeip/pull/4241 but this keeps coming up over and over....

### PR DESCRIPTION
**Pull request by yunhanw-google**
Problem:
Regression issue
Problem
../../src/app/tests/integration/chip_im_initiator.cpp:86:68: error: format specifies type 'unsigned long' but the argument has type 'chip::NodeId' (aka 'unsigned long long') [-Werror,-Wformat]

Summary of changes

Always use PRIu64 for printing uint64_t, including node ids.

Fixes #4284

### CODE REVIEW

**Review by bzbarsky-apple — APPROVED** [review]
Thank you!
