### PR TITLE
Move APP/gen/callback.h to src/app/common/gen/

### PR DESCRIPTION
**Pull request by vivien-apple**
#### Problem

This PR moves `APP/gen/callback.h` to `src/app/common/gen/callback.h` and instead of generating declarations for enabled clusters, it generates declarations for all clusters. 

#### Change overview
 * Move `APP/gen/callback.h` to `src/app/common/gen/callback.h`
 * Generate all declarations of callbacks into `src/app/common/gen/callback.h` since common does not in advance which clusters are enabled and this follow what is done for `af-structs.h`, `enums.h` and friends.
* Use `{{asUpperCamelCase}}` and `{{asLowerCase}}` instead of `{{asCamelCased}}` to avoid issues with cluster names that contains characters not filtered by `{{asCamelCased}}`

#### Testing
There is no feature change, not real code change. This is mostly code beeing shuffled around.

### CODE REVIEW

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by vivien-apple** [comment]
The `Darwin` CI task is failing because of #8021 : 
```
/Users/runner/work/connectedhomeip/connectedhomeip/src/controller/data_model/gen/call-command-handler.cpp:23:10: fatal error: 'callback.h' file not found
```

**Review by jmartinez-silabs — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
@mspang @Damian-Nordic @saurabhst @msandstedt ?

**Review by mspang — APPROVED** [review]

**Review by msandstedt — APPROVED** [review]

**Comment by andy31415** [comment]
@vivien-apple - merge conflicts
