### ISSUE TITLE
Pairing issue with the latest SDK commit using all-clusters-app

### ISSUE THREAD

**Issue by somu1710** [project-chip/connectedhomeip#17323]
Issue :- Not able to advertise the network (ble-wifi/onnetwork) from dut to get paired with controller using all-clusters-app.

Commit used - a75cd99d851cff80e14e753c85f34ff936c84254

commands used for advertising (bringing up dut) : 

Ble-wifi :` connectedhomeip/examples/all-clusters-app/linux/out/all-clusters-app$ ./chip-all-clusters-app --wifi`

Onnetwork : `connectedhomeip/examples/all-clusters-app/linux/out/all-clusters-app$ ./chip-all-clusters-app `

Log:

> ubuntu@matter-te-7:~/connectedhomeip/examples/all-clusters-app/linux/out/all-clusters-app$ ./chip-all-clusters-app 
INTERNAL ERROR: No help text defined for option: -
[1649856140.280266][8986:8986] CHIP:-: Failed to init Linux App: ../../third_party/connectedhomeip/examples/platform/linux/Options.cpp:409: Error 0x0000002F 
[1649856140.280328][8986:8986] CHIP:SPT: VerifyOrDie failure at ../../main.cpp:25: ChipLinuxAppInit(argc, argv, AppOptions::GetOptions()) == 0
Aborted (core dumped)

> ubuntu@matter-te-7:~/connectedhomeip/examples/all-clusters-app/linux/out/all-clusters-app$ ./chip-all-clusters-app --wifi
INTERNAL ERROR: No help text defined for option: -
[1649856349.791896][8990:8990] CHIP:-: Failed to init Linux App: ../../third_party/connectedhomeip/examples/platform/linux/Options.cpp:409: Error 0x0000002F 
[1649856349.791954][8990:8990] CHIP:SPT: VerifyOrDie failure at ../../main.cpp:25: ChipLinuxAppInit(argc, argv, AppOptions::GetOptions()) == 0
Aborted (core dumped)

**Comment by bzbarsky-apple** [comment]
@somu1710 Is this a problem introduced recently?  Of so, would you be able to `git bisect`to find the changeset that introduced it?
